import './globals.css'
import { Poppins } from 'next/font/google'

// Import other dependencies as needed
import Navbar from './Components/Navbar/Navbar'

const poppins = Poppins({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
