import './globals.css'
import {Figtree} from 'next/font/google'
import Navbar from './Components/Navbar/Navbar'
import { Layout } from 'antd/lib'
import Footer from './Components/Footer/page'



const figtree = Figtree({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={figtree.className}>
        <Navbar />
        {children}
       <Footer />
        </body>
    </html>
  )
}
